# Generated by Django 4.1.3 on 2022-12-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fa_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='in_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tw_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
